name: Release Yogusita Themes

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ...
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Package!
        run: npx vsce package

      - name: Get package file name
        id: get_vsix
        run: echo "vsix_name=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Create versioned release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ steps.get_vsix.outputs.vsix_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git for tag update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Move latest tag to current commit
        run: |
          git tag -f latest
          git push origin latest --force

      - name: Create or update latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: ${{ steps.get_vsix.outputs.vsix_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
